# Generated by Django 5.2.6 on 2025-11-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
    ]
